/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.godev.telas;

import java.sql.*;
import br.com.godev.dal.ModuloConexao;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

public class TelaSala extends javax.swing.JInternalFrame {

    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    public TelaSala() {
        initComponents();
        conexao = ModuloConexao.conector();
    }
    //método para adicionar clientes

    private void adicionar() {

        String sql = "insert into tbsalas(nomesala,lotacao) values (?,?)";
        try {

            pst = conexao.prepareStatement(sql);
            pst.setString(1, txtSalNome.getText());
            pst.setString(2, txtSalLot.getText());
            
            if ((txtSalNome.getText().isEmpty()) || (txtSalLot.getText().isEmpty())) {
                JOptionPane.showMessageDialog(null, "Preencha todos os campos obrigatórios");
            } else {
                int adicionado = pst.executeUpdate();

                if (adicionado > 0) {
                    JOptionPane.showMessageDialog(null, "Sala adicionada com sucesso");
                    txtSalNome.setText(null);
                    txtSalLot.setText(null);
                   
                }
            }
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    //pesquisar clientes pelo nome com filtro
    private void pesquisar_salas() {
        String sql = "select * from tbsalas where nomesala like ?";
        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1, txtSalPesquisar.getText() + "%");
            rs = pst.executeQuery();

            tbSalas.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }
// metodo para setar os campos  do formulario com o conteudo da tabela

    public void setar_campos() {
        int setar = tbSalas.getSelectedRow();
        txtIdsal.setText(tbSalas.getModel().getValueAt(setar, 0).toString());
        txtSalNome.setText(tbSalas.getModel().getValueAt(setar, 1).toString());
        txtSalLot.setText(tbSalas.getModel().getValueAt(setar, 2).toString());
        
        // a linha abaixo desabilita o botão adicionar
        btnSalCreate.setEnabled(false);
    }

    //metodo para alterar dados do cliente
    private void alterar() {
        String sql = "update tbsalas set nomesala=?,lotacao=? where idsala=?";
        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1, txtSalNome.getText());
            pst.setString(2, txtSalLot.getText());
            pst.setString(3, txtIdsal.getText());

            if ((txtSalNome.getText().isEmpty()) || (txtSalLot.getText().isEmpty())) {
                JOptionPane.showMessageDialog(null, "Preencha todos os campos obrigatórios");
            } else {
                int adicionado = pst.executeUpdate();

                if (adicionado > 0) {
                    JOptionPane.showMessageDialog(null, "Dados Atualizados com sucesso");
                    txtSalNome.setText(null);
                    txtSalLot.setText(null);
                    btnSalCreate.setEnabled(true);
                }
            }
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    // metodo para remover clientes
    private void remover() {
        // a estrutura abaixo confirma a remoçao do cliente
        int confirma = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja remover essa sala?", "Atenção", JOptionPane.YES_NO_OPTION);
        if (confirma == JOptionPane.YES_OPTION) {
            String sql = "delete from tbsalas where idsala=?";

            try {
                pst = conexao.prepareStatement(sql);
                pst.setString(1, txtIdsal.getText());
                int apagado = pst.executeUpdate();
                if (apagado > 0) {
                    JOptionPane.showMessageDialog(null, "Sala Removida com Sucesso");
                    txtSalNome.setText(null);
                    txtSalLot.setText(null);
                    btnSalCreate.setEnabled(true);
                }
            } catch (HeadlessException | SQLException e) {
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtSalNome = new javax.swing.JTextField();
        txtSalLot = new javax.swing.JTextField();
        btnSalCreate = new javax.swing.JButton();
        btnSalUpdate = new javax.swing.JButton();
        btnSalDelete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtSalPesquisar = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbSalas = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        txtIdsal = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Cadastro De Salas");
        setMinimumSize(new java.awt.Dimension(842, 664));
        setPreferredSize(new java.awt.Dimension(842, 664));

        jLabel2.setText("*NOME SALA:");

        jLabel3.setText("*LOTAÇÃO SALA:");

        txtSalLot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSalLotActionPerformed(evt);
            }
        });

        btnSalCreate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/godev/icones/add.png"))); // NOI18N
        btnSalCreate.setToolTipText("Adicionar");
        btnSalCreate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalCreate.setPreferredSize(new java.awt.Dimension(80, 80));
        btnSalCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalCreateActionPerformed(evt);
            }
        });

        btnSalUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/godev/icones/update.png"))); // NOI18N
        btnSalUpdate.setToolTipText("Alterar");
        btnSalUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalUpdate.setPreferredSize(new java.awt.Dimension(80, 80));
        btnSalUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalUpdateActionPerformed(evt);
            }
        });

        btnSalDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/godev/icones/del.png"))); // NOI18N
        btnSalDelete.setToolTipText("Deletar");
        btnSalDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalDelete.setPreferredSize(new java.awt.Dimension(80, 80));
        btnSalDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalDeleteActionPerformed(evt);
            }
        });

        jLabel1.setText("* Campo Obrigatórios");

        txtSalPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSalPesquisarKeyReleased(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/godev/icones/find.png"))); // NOI18N

        tbSalas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbSalas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbSalasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbSalas);

        jLabel8.setText("ID SALA");

        txtIdsal.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSalLot)
                            .addComponent(txtSalNome, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE))
                        .addGap(266, 437, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(btnSalCreate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118)
                .addComponent(btnSalUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122)
                .addComponent(btnSalDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 205, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSalPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdsal, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(txtSalPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtIdsal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSalNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSalLot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSalCreate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        setBounds(0, 0, 842, 664);
    }// </editor-fold>//GEN-END:initComponents

    private void txtSalLotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSalLotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSalLotActionPerformed

    private void btnSalCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalCreateActionPerformed
        // adicionar clientes
        adicionar();
    }//GEN-LAST:event_btnSalCreateActionPerformed

    private void txtSalPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSalPesquisarKeyReleased
        pesquisar_salas();
    }//GEN-LAST:event_txtSalPesquisarKeyReleased

    private void tbSalasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbSalasMouseClicked
        setar_campos();
    }//GEN-LAST:event_tbSalasMouseClicked

    private void btnSalUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalUpdateActionPerformed
        //alterar clientes
        alterar();
    }//GEN-LAST:event_btnSalUpdateActionPerformed

    private void btnSalDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalDeleteActionPerformed
        // remover pessoas
        remover();
    }//GEN-LAST:event_btnSalDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalCreate;
    private javax.swing.JButton btnSalDelete;
    private javax.swing.JButton btnSalUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbSalas;
    private javax.swing.JTextField txtIdsal;
    private javax.swing.JTextField txtSalLot;
    private javax.swing.JTextField txtSalNome;
    private javax.swing.JTextField txtSalPesquisar;
    // End of variables declaration//GEN-END:variables
}
